name: CDGATenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - blas=1.0=mkl
  - boltons=23.0.0=py38haa95532_0
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2023.7.22=h56e8100_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py38h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.7.4=py38haa244fe_0
  - conda-package-handling=2.1.0=py38haa95532_0
  - conda-package-streaming=0.8.0=py38haa95532_0
  - console_shortcut=0.1.1=4
  - cryptography=39.0.1=py38h21b164f_2
  - cuda-cccl=12.3.52=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.3.52=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.3.1=h280eb24_10
  - filelock=3.9.0=py38haa95532_0
  - freetype=2.4.10=0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.4=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - jinja2=3.1.2=py38haa95532_0
  - jpeg=8d=0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.4.52=0
  - libcurand-dev=10.3.4.52=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.4=hd77b12b_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.17=0
  - libtiff=4.0.2=1
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.2=h2bbff1b_0
  - menuinst=1.4.16=py38he774522_0
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - openssl=3.0.11=h2bbff1b_2
  - packaging=23.1=py38haa95532_0
  - pip=23.1.2=py38haa95532_0
  - platformdirs=3.10.0=py38haa95532_0
  - pluggy=1.0.0=py38haa95532_1
  - pooch=1.7.0=py38haa95532_0
  - powershell_shortcut=0.0.1=3
  - pycosat=0.6.4=py38h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.16=h1aa4202_4
  - python_abi=3.8=2_cp38
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pywin32=305=py38h2bbff1b_0
  - requests=2.29.0=py38haa95532_0
  - ruamel.yaml=0.17.21=py38h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py38h2bbff1b_1
  - ruamel_yaml=0.15.87=py38he774522_0
  - setuptools=67.8.0=py38haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - sympy=1.11.1=py38haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - toolz=0.12.0=py38haa95532_0
  - tqdm=4.65.0=py38hd4e2768_0
  - typing_extensions=4.7.1=py38haa95532_0
  - urllib3=1.26.16=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - yaml=0.1.7=hc54c509_2
  - zlib=1.2.8=0
  - zstandard=0.19.0=py38h2bbff1b_0
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.3
      - blinker==1.8.2
      - blis==0.7.10
      - cachetools==5.3.3
      - catalogue==2.0.9
      - click==8.1.3
      - colorama==0.4.4
      - confection==0.1.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - cymem==2.0.7
      - decorator==5.1.1
      - dgl==1.1.2+cu117
      - docker-pycreds==0.4.0
      - en-core-web-sm==3.6.0
      - et-xmlfile==1.1.0
      - executing==2.1.0
      - flask==3.0.3
      - fonttools==4.40.0
      - frozenlist==1.5.0
      - fsspec==2023.5.0
      - geographiclib==2.1
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.64.0
      - h5py==3.11.0
      - huggingface-hub==0.0.8
      - importlib-metadata==6.8.0
      - importlib-resources==5.12.0
      - ipdb==0.13.9
      - ipython==8.12.3
      - itsdangerous==2.2.0
      - jax==0.4.13
      - jedi==0.19.2
      - joblib==1.2.0
      - jsonlines==2.0.0
      - kiwisolver==1.4.4
      - langcodes==3.3.0
      - llvmlite==0.37.0
      - markdown==3.7
      - markupsafe==2.1.2
      - mat73==0.65
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - ml-dtypes==0.2.0
      - mpmath==1.2.1
      - multidict==6.1.0
      - murmurhash==1.0.9
      - networkx==3.0
      - nltk==3.9.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - openpyxl==3.1.2
      - opt-einsum==3.4.0
      - pandas==1.4.4
      - parso==0.8.4
      - pathtools==0.1.2
      - pathy==0.10.2
      - patsy==1.0.2
      - pickleshare==0.7.5
      - pillow==9.0.0
      - plotly==5.22.0
      - preshed==3.0.8
      - prettytable==3.11.0
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==4.24.4
      - psutil==5.9.6
      - pure-eval==0.2.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==1.10.12
      - pygments==2.18.0
      - pymap3d==3.1.0
      - pynvml==11.5.3
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyvista==0.44.2
      - pyyaml==6.0
      - regex==2023.5.5
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - sacremoses==0.0.53
      - safetensors==0.3.1
      - scikit-learn==1.2.2
      - scikit-posthocs==0.8.1
      - scipy==1.10.1
      - scooby==0.11.0
      - seaborn==0.13.2
      - sentry-sdk==1.32.0
      - setproctitle==1.3.3
      - shapely==2.0.7
      - six==1.16.0
      - smart-open==6.3.0
      - smmap==5.0.1
      - soupsieve==2.6
      - spacy==3.6.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - spacy-pkuseg==0.0.32
      - srsly==2.4.7
      - stack-data==0.6.3
      - statsmodels==0.14.0
      - tabulate==0.9.0
      - tenacity==8.3.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - texttable==1.7.0
      - thinc==8.1.10
      - thop==0.1.1-2209072238
      - threadpoolctl==3.1.0
      - tokenizers==0.10.3
      - toml==0.10.2
      - torch==1.12.0+cu116
      - torch-geometric==2.6.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - traitlets==5.14.3
      - transformers==4.7.0
      - trimesh==4.9.0
      - typer==0.9.0
      - typing-extensions==4.4.0
      - tzdata==2023.3
      - vtk==9.3.1
      - wandb==0.15.12
      - wasabi==1.1.2
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - wget==3.2
      - wordcloud==1.9.4
      - yarl==1.15.2
      - zh-core-web-sm==3.6.0
      - zipp==3.15.0
prefix: D:\PyCharm\miniConda
